import Head from 'next/head';
import Message from '../components/message';
import { useState, useEffect } from 'react';
import { db } from '../utils/firebase';
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';
import Link from 'next/link';

export default function Home() {
  // create a state with all the posts
  const [allPosts, setAllPosts] = useState([]);
  const getPosts = (async) => {
    const collectionRef = collection(db, 'posts');
    const q = query(collectionRef, orderBy('timestamp', 'desc'));
    const unsubcribe = onSnapshot(q, (snappshot) => {
      setAllPosts(snappshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });
    return unsubcribe;
  };

  useEffect(() => {
    getPosts();
  }, []);

  return (
    <div>
      <Head>
        <title>AxifivethChat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="my-12 text-lg font-medium">
        <h2 className="">Mari kita mencari teman</h2>
        {allPosts.map((post) => (
          <>
            <Message {...post} key={post.id}>
              <Link href={{ pathname: '/${post.id}', query: { ...post } }}>
                <button>{post.comments?.length > 0 ? post.comments?.length : 0} Comments</button>
              </Link>
            </Message>
          </>
        ))}
      </div>
    </div>
  );
}
